service: palmera-files

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${.env:NODE_ENV}
    MONGODB_URI: ${.env:MONGODB_URI}
    JWT_SECRET: ${.env:JWT_SECRET}
    AWS_S3_BUCKET_NAME: ${.env:AWS_S3_BUCKET_NAME}
    AWS_ACCESS_KEY_ID: ${.env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${.env:AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${.env:AWS_REGION}

functions:
  uploadFile:
    handler: src/handlers/uploadFileHandler.handler
    events:
      - http:
          path: /files/upload
          method: post
          cors: true
          authorizer:
            name: verifyToken
            type: token

  getFile:
    handler: src/handlers/getFileHandler.handler
    events:
      - http:
          path: /files/{id}
          method: get
          cors: true
          authorizer:
            name: verifyToken
            type: token

  deleteFile:
    handler: src/handlers/deleteFileHandler.handler
    events:
      - http:
          path: /files/{id}
          method: delete
          cors: true
          authorizer:
            name: verifyToken
            type: token

  verifyToken:
    handler: ../auth/src/middlewares/authMiddleware.verifyToken

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!.gitignore'
    - '!.env*'
    - '!README.md'
    - '!tests/**'
    - '!coverage/**'