service: palmera-bookings

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${.env:NODE_ENV}
    MONGODB_URI: ${.env:MONGODB_URI}
    JWT_SECRET: ${.env:JWT_SECRET}
    AWS_S3_BUCKET_NAME: ${.env:AWS_S3_BUCKET_NAME}

functions:
  createBookings:
    handler: src/handlers/createBookingHandler.handler
    events:
      - http:
          path: /bookings
          method: post
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

  getBookings:
    handler: src/handlers/getBookingHandler.handler
    events:
      - http:
          path: /bookings/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

  updateBookings:
    handler: src/handlers/updateBookingHandler.handler
    events:
      - http:
          path: /bookings/{id}
          method: put
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

  getUserBookings:
    handler: src/handlers/getUserBookingsHandler.handler
    events:
      - http:
          path: /bookings/user/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

  getHostBookings:
    handler: src/handlers/getHostBookingsHandler.handler
    events:
      - http:
          path: /bookings/host/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

  cancelBooking:
    handler: src/handlers/cancelBookingHandler.handler
    events:
      - http:
          path: /bookings/{id}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

  getUserPastBookings:
    handler: src/handlers/getUserBookingHistoryHandler.handler
    events:
      - http:
          path: /bookings/history/user/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

  getHostPastBookings:
    handler: src/handlers/getHostBookingHistoryHandler.handler
    events:
      - http:
          path: /bookings/history/host/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: '400'
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
    GatewayResponseDefault5XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: '500'
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"

package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.env*'
    - '!README.md'
    - '!tests/**'
    - '!coverage/**'
