service: palmera-messaging

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${.env:NODE_ENV}
    MONGODB_URI: ${.env:MONGODB_URI}
    JWT_SECRET: ${.env:JWT_SECRET}
    AWS_S3_BUCKET_NAME: ${.env:AWS_S3_BUCKET_NAME}

functions:
  sendMessage:
    handler: src/handlers/sendMessageHandler.handler
    events:
      - http:
          path: /messages
          method: post
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

  getMessages:
    handler: src/handlers/getConversationMessagesHandler.handler
    events:
      - http:
          path: /messages/conversation/{conversationId}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

  getUserConversations:
    handler: src/handlers/getUserConversationsHandler.handler
    events:
      - http:
          path: /conversations/user/{userId}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

  deleteMessage:
    handler: src/handlers/deleteMessageHandler.handler
    events:
      - http:
          path: /messages/{messageId}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:850995537590:function:palmera-auth-dev-verifyToken
            type: token

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.env*'
    - '!README.md'
    - '!tests/**'
    - '!coverage/**'
