service: palmera-properties

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${.env:NODE_ENV}
    MONGODB_URI: ${.env:MONGODB_URI}
    JWT_SECRET: ${.env:JWT_SECRET}
    AWS_S3_BUCKET_NAME: ${.env:AWS_S3_BUCKET_NAME}

functions:
  createProperty:
    handler: src/handlers/createPropertyHandler.handler
    events:
      - http:
          path: /properties
          method: post
          cors: true
          authorizer:
            name: verifyToken
            type: token

  getProperty:
    handler: src/handlers/getPropertyHandler.handler
    events:
      - http:
          path: /properties/{id}
          method: get
          cors: true

  updateProperty:
    handler: src/handlers/updatePropertyHandler.handler
    events:
      - http:
          path: /properties/{id}
          method: put
          cors: true
          authorizer:
            name: verifyToken
            type: token
  getUserProperty:
    handler: src/handlers/getUserPropertiesHandler.handler
    events:
      - http:
          path: /properties/user/{id}
          method: get
          cors: true

  deleteProperty:
    handler: src/handlers/deletePropertyHandler.handler
    events:
      - http:
          path: /properties/{id}
          method: delete
          cors: true
          authorizer:
            name: verifyToken
            type: token

  searchProperties:
    handler: src/handlers/searchPropertiesHandler.handler
    events:
      - http:
          path: /properties/search
          method: get
          cors: true
  uploadPropertyDocument:
    handler: src/handlers/uploadPropertyDocumentsHandler.handler
    timeout: 90
    events:
      - http:
          path: /properties/{id}/documents
          method: post
          cors: true
          authorizer:
            name: verifyToken
            type: token
  uploadPropertyImages:
    handler: src/handlers/uploadPropertyImagesHandler.handler
    timeout: 90
    events:
      - http:
          path: /properties/{id}/images
          method: post
          cors: true
          authorizer:
            name: verifyToken
            type: token
  deletePropertyDocument:
    handler: src/handlers/deletePropertyDocumentHandler.handler
    events:
      - http:
          path: /properties/{id}/documents/{docId}
          method: delete
          cors: true
          authorizer:
            name: verifyToken
            type: token
  deletePropertyImages:
    handler: src/handlers/deletePropertyImagesHandler.handler
    events:
      - http:
          path: /properties/{id}/images
          method: delete
          cors: true
          authorizer:
            name: verifyToken
            type: token
  verifyToken:
    handler: ../auth/src/middlewares/authMiddleware.verifyToken

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!.gitignore'
    - '!.env*'
    - '!README.md'
    - '!tests/**'
    - '!coverage/**'
