service: palmera-messaging

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${.env:NODE_ENV}
    MONGODB_URI: ${.env:MONGODB_URI}
    JWT_SECRET: ${.env:JWT_SECRET}
    AWS_S3_BUCKET_NAME: ${.env:AWS_S3_BUCKET_NAME}

functions:
  getUsers:
    handler: src/handlers/getUsersHandler.handler
    events:
      - http:
          path: /admin/users
          method: get
          cors: true
          authorizer:
            name: verifyToken
            type: token
  updateUser:
    handler: src/handlers/updateUserHandler.handler
    events:
      - http:
          path: /admin/user/{id}
          method: put
          cors: true
          authorizer:
            name: verifyToken
            type: token
  getProperties:
    handler: src/handlers/getPropertiesForModerationHandler.handler
    events:
      - http:
          path: /admin/properties
          method: get
          cors: true
          authorizer:
            name: verifyToken
            type: token
  updateProperty:
    handler: src/handlers/updatePropertyHandler.handler
    events:
      - http:
          path: /admin/property/{id}
          method: put
          cors: true
          authorizer:
            name: verifyToken
            type: token

  deleteProperty:
    handler: src/handlers/deletePropertyHandler.handler
    events:
      - http:
          path: /admin/property/{id}
          method: delete
          cors: true
          authorizer:
            name: verifyToken
            type: token
  
  verifyToken:
    handler: ../auth/src/middlewares/authMiddleware.verifyToken

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.env*'
    - '!README.md'
    - '!tests/**'
    - '!coverage/**'

